spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: PhoneShop_owner
    password: shop123
  jpa:
    properties:
       hibernate: 
          dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate: 
       ddl-auto: update